
spring:
  datasource:
    url: jdbc:mysql://dev.cfti8umsjnvm.ap-southeast-1.rds.amazonaws.com:3306/config_center?zeroDateTimeBehavior=convertToNull&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Manila&allowMultiQueries=true&socketTimeout=180000&connectTimeout=60000
    username: dev
    password: C1ggDWAxG2fv

configcenter:
  redis:
    host: 192.168.11.21
    port: 6379
    password: